language: cpp
before_script:
  - sudo apt-get install libboost-test-dev -y
  - sudo apt-get install cmake
script:
    - cmake .
    - cmake --build .
    - cmake --build . --target test
    - cmake --build . --target package
