language: cpp
before_script:
  - sudo apt-get install libboost-test-dev -y
  - sudo apt-get install cmake
script:
    - cmake .
    - cmake --build .
    - cmake --build . --target test
    - cmake --build . --target package
    - ls -la

deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T cmake_ci-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ultaa:5507fb3cb5835ea13b39b18546f71c638549455e https://api.bintray.com/content/ltaa/ltaa_cpp/cmake_ci/-0.0.${TRAVIS_BUILD_NUMBER}/otus
